# Generated by Django 4.2.7 on 2024-07-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_country_profile_cv_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('data_analysis', 'Data Analysis'), ('renewable_energy', 'Renewable Energy'), ('cyber_security', 'Cyber Security'), ('iot', 'Internet Of Things')], default='data_analysis', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='learner', max_length=50),
        ),
    ]
