# Generated by Django 5.0.6 on 2024-07-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Mimi', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='125', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='abc1', max_length=50),
        ),
    ]
